### ISSUE TITLE
cxt_dic_path and class_dic_path json files

### ISSUE THREAD

**Issue by Rakshith606** [Wangt-CN/CaaM#1]
cxt_dic_path and class_dic_path json files are not present in NICO.zip

**Comment by Wangt-CN** [comment]
Hi, sorry for that and I have just fixed the share link.

**Comment by Rakshith606** [comment]
Thank you for your quick response.

**Comment by JLINEkai** [comment]
What is your data structure of ImageNet9

**Comment by Wangt-CN** [comment]
Hi, we just follow the original ImageNet9 structure. You can check more details in this paper [1]. Thanks.

[1] Learning de-biased representations with biased representations.
